# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9fbd8a2c309dec4ea2575d91eef1c30a8083e7a4ddc692f9478e2ac8f77e01e8ed6de235f15c194b4bb2eea47a52cfea328ec7306f8b260b8abaeb5483c7540

test:
  secret_key_base: f1927e2d9c32d4fbb7b0d7e4332443183c70f2dd0dad94bcdc61aadf7548fb0236df40ff194c3007325acc6dd08ee1fa1b30fbb3c9e763ad4cd1fbf32663d6dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
